'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class establecimiento
    Public Property idEstablecimiento As Integer
    Public Property Nombre As String
    Public Property Rector As String
    Public Property Seccion As String
    Public Property Tipo As String
    Public Property Resoloucion As String
    Public Property Descripcion As String
    Public Property Direccion As String
    Public Property Telefono As String
    Public Property Web As String
    Public Property Mision As String
    Public Property Vision As String
    Public Property HImno As String
    Public Property Escudo As Byte()
    Public Property Correo As String

End Class
