'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class matricula_alumno
    Public Property ID As Integer
    Public Property Nombre As String
    Public Property Apellidos As String
    Public Property cedula As String
    Public Property lugar_nacimiento As String
    Public Property direccion As String
    Public Property telefono As String
    Public Property estado_civil As String
    Public Property correo As String
    Public Property Periodo As String
    Public Property Curso As String
    Public Property Paralelo As String
    Public Property fecha As Date

End Class
