'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class matricula_representante1
    Public Property ID As Integer
    Public Property Estudiante As String
    Public Property Representante As String
    Public Property Cedula As String
    Public Property correo As String
    Public Property CorreoTrabajo As String
    Public Property TelefonoTrabajo As String
    Public Property telefono As String
    Public Property NiveldeEducacion As String
    Public Property Ocupacion As String
    Public Property viveEstudiante As String
    Public Property relacion As String
    Public Property Periodo As String
    Public Property Curso As String
    Public Property Paralelo As String
    Public Property cedulaestudiante As String
    Public Property Curso2 As String
    Public Property correoestudiante As String

End Class
