'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class rubro
    Public Property idRubros As Integer
    Public Property Detalle As Integer
    Public Property Costo As Decimal
    Public Property Fecha_registro As Nullable(Of Date)
    Public Property Fecha_de_pago As Date
    Public Property Estado As String = "A"
    Public Property idUsuario As Integer

    Public Overridable Property cuotas As ICollection(Of cuota) = New HashSet(Of cuota)
    Public Overridable Property rubros_det As rubros_det

End Class
