'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class rubros_completo
    Public Property ID As Integer
    Public Property Costo As Decimal
    Public Property Fecha_de_pago As Date
    Public Property idUsuario As Integer
    Public Property Detalle As String
    Public Property Estado As String

End Class
