'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class usuario
    Public Property idUsuario As Integer
    Public Property Username As String
    Public Property Password As String
    Public Property idPersona As Integer
    Public Property Desde As Nullable(Of Date)
    Public Property Hasta As Nullable(Of Date)
    Public Property Estado As String = "A"

    Public Overridable Property perfil_usuario As ICollection(Of perfil_usuario) = New HashSet(Of perfil_usuario)
    Public Overridable Property persona As persona

End Class
