'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class zanual_pagos_meses
    Public Property idmatricula As Integer
    Public Property idcuotas As Integer
    Public Property detalle As String
    Public Property Suma As Long
    Public Property Pagar As Decimal
    Public Property descuento As Integer
    Public Property estudiante As String
    Public Property representante As String
    Public Property cedula As String
    Public Property periodo As String
    Public Property Curso As String
    Public Property telefono As String
    Public Property direccion As String

End Class
