'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class curso_completo
    Public Property ID As Integer
    Public Property Curso As String
    Public Property Paralelo As String
    Public Property Estado As String
    Public Property Capacidad As Nullable(Of Integer)

End Class
