'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class curso_paralelo
    Public Property idcurso_paralelo As Integer
    Public Property idCurso As Nullable(Of Integer)
    Public Property idParalelo As Nullable(Of Integer)
    Public Property Estado As String = "A"
    Public Property idUsuario As Nullable(Of Integer)
    Public Property capacidad As Nullable(Of Integer)

    Public Overridable Property matriculas As ICollection(Of matricula) = New HashSet(Of matricula)
    Public Overridable Property curso As curso
    Public Overridable Property paralelo As paralelo

End Class
