'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class estudiante_madre
    Public Property IDEstudiante As Integer
    Public Property idRepresentante As Integer
    Public Property Representante As String
    Public Property Cedula As String
    Public Property correo As String
    Public Property CorreoTrabajo As String
    Public Property TelefonoTrabajo As String
    Public Property telefono As String
    Public Property NiveldeEducacion As String
    Public Property Ocupacion As String
    Public Property viveEstudiante As String

End Class
