'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class factura_detalles
    Public Property idmatricula As Integer
    Public Property idfact_cab As Integer
    Public Property total As Decimal
    Public Property cantidad As Decimal
    Public Property detalle As String
    Public Property idrubros As Integer

End Class
