'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure

Partial Public Class simpp_maarEntities
    Inherits DbContext

    Public Sub New()
        MyBase.New("name=simpp_maarEntities")
    End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
        Throw New UnintentionalCodeFirstException()
    End Sub

    Public Overridable Property ciudads() As DbSet(Of ciudad)
    Public Overridable Property cuotas() As DbSet(Of cuota)
    Public Overridable Property cursos() As DbSet(Of curso)
    Public Overridable Property estudiantes() As DbSet(Of estudiante)
    Public Overridable Property fact_cab() As DbSet(Of fact_cab)
    Public Overridable Property fact_det() As DbSet(Of fact_det)
    Public Overridable Property matriculas() As DbSet(Of matricula)
    Public Overridable Property nacionalidads() As DbSet(Of nacionalidad)
    Public Overridable Property paralelos() As DbSet(Of paralelo)
    Public Overridable Property perfils() As DbSet(Of perfil)
    Public Overridable Property perfil_usuario() As DbSet(Of perfil_usuario)
    Public Overridable Property periodoes() As DbSet(Of periodo)
    Public Overridable Property personas() As DbSet(Of persona)
    Public Overridable Property representantes() As DbSet(Of representante)
    Public Overridable Property rubros() As DbSet(Of rubro)
    Public Overridable Property usuarios() As DbSet(Of usuario)
    Public Overridable Property establecimientoes() As DbSet(Of establecimiento)
    Public Overridable Property estudiantepersonas() As DbSet(Of estudiantepersona)
    Public Overridable Property representante_estudiante1() As DbSet(Of representante_estudiante1)
    Public Overridable Property representante_persona() As DbSet(Of representante_persona)
    Public Overridable Property representantecompletoes() As DbSet(Of representantecompleto)
    Public Overridable Property matricula_completa() As DbSet(Of matricula_completa)
    Public Overridable Property curso_paralelo() As DbSet(Of curso_paralelo)
    Public Overridable Property curso_completo() As DbSet(Of curso_completo)
    Public Overridable Property usuario_completo() As DbSet(Of usuario_completo)
    Public Overridable Property staffs() As DbSet(Of staff)
    Public Overridable Property perfiles() As DbSet(Of perfile)
    Public Overridable Property rubros_det() As DbSet(Of rubros_det)
    Public Overridable Property rubros_completo() As DbSet(Of rubros_completo)
    Public Overridable Property cuotas_completa() As DbSet(Of cuotas_completa)
    Public Overridable Property estudiante_madre() As DbSet(Of estudiante_madre)
    Public Overridable Property estudiante_padre() As DbSet(Of estudiante_padre)
    Public Overridable Property matricula_alumno() As DbSet(Of matricula_alumno)
    Public Overridable Property matricula_representante1() As DbSet(Of matricula_representante1)
    Public Overridable Property zcabeceras() As DbSet(Of zcabecera)
    Public Overridable Property factura_detalles() As DbSet(Of factura_detalles)
    Public Overridable Property zcuotas_matricula() As DbSet(Of zcuotas_matricula)
    Public Overridable Property zcuotas_meses() As DbSet(Of zcuotas_meses)
    Public Overridable Property curso_completo_nombres_unidos() As DbSet(Of curso_completo_nombres_unidos)
    Public Overridable Property zpagosmensuales() As DbSet(Of zpagosmensuale)
    Public Overridable Property zanual_pagos_matricula() As DbSet(Of zanual_pagos_matricula)
    Public Overridable Property zanual_pagos_meses() As DbSet(Of zanual_pagos_meses)
    Public Overridable Property matriculas_inactivas() As DbSet(Of matriculas_inactivas)

End Class
