'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class paralelo
    Public Property idParalelos As Integer
    Public Property Detalle As String
    Public Property Estado As String = "A"
    Public Property idUsuario As Integer

    Public Overridable Property curso_paralelo As ICollection(Of curso_paralelo) = New HashSet(Of curso_paralelo)

End Class
