'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class perfil_usuario
    Public Property idPerfil_usuario As Integer
    Public Property idPerfil As Integer
    Public Property idUsuario As Integer
    Public Property Estado As String = "A"

    Public Overridable Property perfil As perfil
    Public Overridable Property usuario As usuario

End Class
