'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class representante_estudiante1
    Public Property id As Integer
    Public Property idRepresentante As Nullable(Of Integer)
    Public Property idEstudiante As Nullable(Of Integer)
    Public Property Estado As String = "A"

    Public Overridable Property estudiante As estudiante
    Public Overridable Property representante As representante

End Class
