'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class rubros_det
    Public Property idrubros_det As Integer
    Public Property Detalle As String
    Public Property Estado As String
    Public Property idUsuario As Nullable(Of Integer)

    Public Overridable Property rubros As ICollection(Of rubro) = New HashSet(Of rubro)

End Class
