'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class zcabecera
    Public Property id As Integer
    Public Property estudiante As String
    Public Property representante As String
    Public Property cedula As String
    Public Property periodo As String
    Public Property curso As String
    Public Property paralelo As String
    Public Property telefono As String
    Public Property direccion As String
    Public Property idfact_cab As Integer
    Public Property fecha As Date

End Class
